version: '3'

services:
  backend:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=your_mongo_uri_here
      - JWT_SECRET=your_jwt_secret_here
    volumes:
      - ./server:/app
    restart: always

  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app
    restart: always
    command: npm run dev
